### ISSUE TITLE
调用notifyDataChanged()崩溃

### ISSUE THREAD

**Issue by jiang1654** [MagicMashRoom/SuperCalendar#121]
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                      at java.util.ArrayList.get(ArrayList.java:310)
                                                                      at com.ldf.calendar.component.CalendarViewAdapter.refreshCalendar(CalendarViewAdapter.java:256)
                                                                      at com.ldf.calendar.component.CalendarViewAdapter.notifyDataChanged(CalendarViewAdapter.java:223)
                                                                      at com.btten.doctor.ui.main.fragment.fragmenthomepage.FragmentCalendar$5.onSuccess(FragmentCalendar.java:411)
                                                                      at com.btten.doctor.http.subscriber.HttpManager$10.onResponse(HttpManager.java:397)
                                                                      at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by ZaneSummer** [comment]
我也是这个 你解决了吗

**Comment by pcegarra** [comment]
same problem here
