### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Tforandroid** [MagicMashRoom/SuperCalendar#124]
Caused by: java.lang.NullPointerException
                                                                 at android.view.LayoutInflater.from(LayoutInflater.java:210)
                                                                 at com.ldf.calendar.view.DayView.setupLayoutResource(DayView.java:44)

 public DayView(Context context, int layoutResource) {
        super(context);
        setupLayoutResource(layoutResource);
        this.context = context;
        this.layoutResource = layoutResource;
    }

  private void setupLayoutResource(int layoutResource) {
  View inflated = LayoutInflater.from(context).inflate(layoutResource, this);
｝

**Comment by Tforandroid** [comment]
this.context = context;
setupLayoutResource(layoutResource);
