### ISSUE TITLE
Cant change current data programmatically

### ISSUE THREAD

**Issue by pcegarra** [MagicMashRoom/SuperCalendar#135]
Im calling
`        calendarAdapter.notifyDataChanged(date);
`with the error 
```
  java.lang.ArrayIndexOutOfBoundsException: length=5; index=-1
at java.util.ArrayList.get(ArrayList.java:439)
at com.ldf.calendar.component.CalendarViewAdapter.refreshCalendar(CalendarViewAdapter.java:256)
at com.ldf.calendar.component.CalendarViewAdapter.notifyDataChanged(CalendarViewAdapter.java:219)
```

**Comment by pcg92** [comment]
Im losing a lot of time with this problem

`    java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                                           at java.util.ArrayList.get(ArrayList.java:413)
                                                                           at com.ldf.calendar.component.CalendarViewAdapter.switchToWeek(CalendarViewAdapter.java:189)`
