### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by wujianwei121** [MagicMashRoom/SuperCalendar#49]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.ldf.calendar.component.CalendarViewAdapter.getPagers()' on a null object reference
                                                                       at com.ldf.calendar.view.MonthPager.getTopMovableDistance(MonthPager.java:125)
                                                                       at com.ldf.calendar.behavior.MonthPagerBehavior.onDependentViewChanged(MonthPagerBehavior.java:73)
                                                                       at com.ldf.calendar.behavior.MonthPagerBehavior.onDependentViewChanged(MonthPagerBehavior.java:16)
                                                                       at android.support.design.widget.CoordinatorLayout.onChildViewsChanged(CoordinatorLayout.java:1336)
                                                                       at android.support.design.widget.CoordinatorLayout$OnPreDrawListener.onPreDraw(CoordinatorLayout.java:1907)
                                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2412)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1303)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6688)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:822)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:625)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:594)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:808)
                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                       at android.os.Looper.loop(Looper.java:194)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5714)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

我按着demo写的   但是我只抽取了<android.support.design.widget.CoordinatorLayout></>日历   代码也完全复制过来了   望解答

**Comment by wujianwei121** [comment]
public class ScheduleFragment extends BaseTitleFragment {
    @BindView(R.id.calendar_view)
    MonthPager monthPager;
    @BindView(R.id.list)
    RecyclerView rvToDoList;
    @BindView(R.id.content)
    CoordinatorLayout content;
    Unbinder unbinder;
    private int mCurrentPage = MonthPager.CURRENT_DAY_INDEX;
    private ArrayList<Calendar> currentCalendars = new ArrayList<>();
    private CalendarDate currentDate;
    private CalendarViewAdapter calendarAdapter;
    private OnSelectDateListener onSelectDateListener;

    @Override
    protected void initData() {

    }

    @Override
    protected int getContentLayout() {
        return R.layout.fragment_schedule;
    }

    @Override
    protected void initView() {
        rvToDoList.setHasFixedSize(true);
        //这里用线性显示 类似于listview
        rvToDoList.setLayoutManager(new LinearLayoutManager(context));
        rvToDoList.setAdapter(new ExampleAdapter(context));
        //此处强行setViewHeight，毕竟你知道你的日历牌的高度
        monthPager.setViewheight(Utils.dpi2px(context, 270));
        initCurrentDate();
        initCalendarView();

    }

    private void initCurrentDate() {
        currentDate = new CalendarDate();
    }

    /**
     * 初始化标记数据，HashMap的形式，可自定义
     *
     * @return void
     */
    private void initMarkData() {
        HashMap<String, String> markData = new HashMap<>();
        markData.put("2017-8-9", "1");
        markData.put("2017-7-9", "0");
        markData.put("2017-6-9", "1");
        markData.put("2017-6-10", "0");
        calendarAdapter.setMarkData(markData);
    }

    private void initCalendarView() {
        initListener();
        CustomDayView customDayView = new CustomDayView(
                getContext(), R.layout.custom_day);
        calendarAdapter = new CalendarViewAdapter(
                getContext(),
                onSelectDateListener,
                CalendarAttr.CalendayType.MONTH,
                customDayView);
        Logger.d("calendarAdapter---------------------------------------------------");
        initMarkData();
        initMonthPager();
    }

    private void initListener() {
        onSelectDateListener = new OnSelectDateListener() {
            @Override
            public void onSelectDate(CalendarDate date) {
            }

            @Override
            public void onSelectOtherMonth(int offset) {
                //偏移量 -1表示刷新成上一个月数据 ， 1表示刷新成下一个月数据
                monthPager.selectOtherMonth(offset);
            }
        };
    }

    private void initMonthPager() {
        monthPager.setAdapter(calendarAdapter);
        monthPager.setCurrentItem(MonthPager.CURRENT_DAY_INDEX);
        monthPager.setPageTransformer(false, new ViewPager.PageTransformer() {
            @Override
            public void transformPage(View page, float position) {
                position = (float) Math.sqrt(1 - Math.abs(position));
                page.setAlpha(position);
            }
        });
        monthPager.addOnPageChangeListener(new MonthPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                mCurrentPage = position;
                currentCalendars = calendarAdapter.getPagers();
                if (currentCalendars.get(position % currentCalendars.size()) instanceof Calendar) {
                    CalendarDate date = currentCalendars.get(position % currentCalendars.size()).getSeedDate();
                    currentDate = date;
                }
            }

            @Override
            public void onPageScrollStateChanged(int state) {
            }
        });
    }


    @Override
    protected String getCommonTitle() {
        return "排期";
    }

    @Override
    protected boolean isUseEventBus() {
        return true;
    }

    @Subscribe
    public void onEventMainThread(String eb) {
        if (eb.equals("windowfocuschange")) {
            Logger.d("windowfocuschange---------------------------------------------------");
            CalendarDate today = new CalendarDate();
            calendarAdapter.notifyDataChanged(today);
        }
    }
