### ISSUE TITLE
fragmennt切换回来后返回今日报索引越界

### ISSUE THREAD

**Issue by overtruer** [MagicMashRoom/SuperCalendar#51]
在fragment里面使用日历,来回切换fragment,返回今日报错,
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                             at java.util.ArrayList.get(ArrayList.java:310)
                                                                             at com.ldf.calendar.component.CalendarViewAdapter.notifyDataChanged(CalendarViewAdapter.java:232)

**Comment by overtruer** [comment]
只是调用了
calendarAdapter.notifyDataChanged(new CalendarDate());

**Comment by yanxinmiao** [comment]
怎么解决的呢
