### ISSUE TITLE
  java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

### ISSUE THREAD

**Issue by yanxinmiao** [MagicMashRoom/SuperCalendar#65]
```
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
at java.util.ArrayList.get(ArrayList.java:310)
at com.ldf.calendar.component.CalendarViewAdapter.notifyDataChanged(CalendarViewAdapter.java:245) 
at com.hudong.baikejiemi.activity.SignInActivity.refreshMonthPager(SignInActivity.java:202)
at com.hudong.baikejiemi.activity.SignInActivity.access$300

```
从接口请求会日期后，加到markdata中，然后刷新 ，就报错了

```
markData.add(s.getSigned_at());
calendarAdapter.setMarkData(markData);
refreshMonthPager();
```

**Comment by ma969070578** [comment]
calendarAdapter.invalidateCurrentCalendar();
  这样调用~
